version: "3.7"

services:
  server:
    build: .
    ports:
      - 9000:9000
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - /var/recipedia/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - /var/recipedia/data:/dgraph
      - ./db/launch-alpha.sh:/dgraph/launch-alpha.sh
      - type: bind
        source: ./db/data
        target: /dgraph/data
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: bash /dgraph/launch-alpha.sh
  ratel:
    image: dgraph/dgraph:latest
    ports:
      - 8000:8000
    command: dgraph-ratel
